name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a
        # healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        env:
          ZTF_USERNAME: ${{ secrets.ZTF_USERNAME }}
          ZTF_PASSWORD: ${{ secrets.ZTF_PASSWORD }}

        run: python -m pytest tests/obs/test_ztf.py
